export const aliments: Record<string, string> = {
  "le pain": "het brood",
  "la tartine": "de boterham",
  "le sandwich": "de sandwich",
  "le croissant": "de croissant",
  "le beignet": "de donut",

  "la baguette": "het stokbrood",
  "le riz": "de rijst",
  "l'oeuf": "het ei",
  "les frites": "de frieten",
  "les pâtes": "de deegwaren, de pasta",
  "les spaghettis": "de spaghetti",
  "la pizza": "de pizza",
  "le hotdog": "de hotdog",
  "la pâte à tartiner": "de choco",
  "le beurre de cacahuète": "de pindakaas",
  "la confiture": "de confituur",
  "le fromage": "de kaas",
  "le yaourt": "de yoghurt",
  "le beurre": "de boter",


  "la compote": "de vruchtenmoes",
  "l'huile d'olive ": "de olijfolie",
  "le sel": "het zout",
  "le poivre": "de peper",
  "le ketchup": "de ketchup",
  "la mayonnaise": "de mayonaise",
  "la moutarde": "de mosterd",
  "le sucre": "de suiker",
  "le cupcake": "de cupcake",
  "le chocolat": "de chocolade",
  "la glace": "het ijs",

  "les chips": "de chips",
  "le gâteau": "het gebak",
  "la tarte": "de taart",
  "le bonbon, la friandise": "het snoepje, het snoepgoed",
  "le popcorn": "de popcorn",
};