export const cuisines: Record<string, string> = {
  "le four": "de oven",
  "le microonde": "de microgolfoven",
  "le frigo": "de koelkast",
  "le congélateur": "de diepvriezer",
  "le lave-vaisselle": "de vaatwasser",
  "l'évier": "de gootsteen",
  "le mixeur": "de mixer",
  "le robot": "de keukenrobot",
  "la balance": "de weegschaal",
  "la poubelle": "de vuilnisbak",
  "le fouet": "de garde, de klopper",
  "le couvert": "het bestek",
  "le couteau": "het mes",
  "la fourchette": "de vork",
  "la cuillère": "de lepel",
  "la cuillère à soupe": "de soeplepel",
  "la cuillère à café": "de koffielepel",
  "la louche": "de pollepel",
  "le bol": "de kom",
  "la bouteille": "de fles",
  "la planche, la planche à découper": "de snijplank",
  "la poêle": "de pan",
  "la casserole": "de kookpot",
  "la tasse": "het kopje",
  "le verre": "het glas",
  "le tablier": "de schort",
  "l'assiette": "het bord",
  "la serviette": "het servet",
  "le moule": "de bakvorm",
  "la cuisinière": "het fornuis",

  "mélanger": "mengen",
  "ajouter": "toevoegen",
  "battre": "opkloppen",
  "verser": "gieten",
  "couper": "snijden",
  "casser": "breken",
  "cuire": "bakken",
  "laver": "wassen",
  "mettre": "zetten, leggen, plaatsen",
  "utiliser": "gebruiken",
  "refroidir": "afkoelen",
  "servir": "opdienen",
  "fondre": "smelten",
  "sortir": "uithalen",
  "déguster": "proeven, eten",
  "éplucher  ": "schillen",
};