export const livre: Record<string, string> = {
  "le livre": "het boek",
  "la bulle": "de tekstballon",
  "le personnage": "het personage",
  "l'onomatopée": "de onomatopee",
  "le titre": "de titel",
  "l'écrivain": "de schrijver",
  "l'écrivaine": "de schrijfster",
  "l'auteur": "de auteur",
  "le résumé": "de samenvatting",
  "le prix": "de prijs",
  "l'illustration": "de illustratie",
  "la couverture": "de omslag, de cover",
  "la page": "de pagina",
  "le texte": "de tekst",
  "le chapitre  ": "het hoofdstuk",
  "le lecteur, la lectrice": "de lezer, de lezeres",
  "la librairie": "de boekenwinkel",
  "la bibliothèque": "de bibliotheek",
  "le roman": "de roman",
  "la B.D., la bande dessinée": "de strip, het stripverhaal",
  "le livre pour enfants": "het kinderboek",
  "le livre pour la jeunesse": "het jeugdboek",
  "le livre scolaire": "het schoolboek",
  "le dictionnaire": "het woordenboek",
  "le livre de cuisine": "het kookboek",
  "l'atlas": "de atlas",
};
