export const meubles: Record<string, string> = {
  "le bureau": "de bureau",
  "la chaise de bureau": "de bureaustoel",
  "le canapé": "de zitbank, de zetel",
  "le fauteuil": "de eenzit",
  "l'armoire": "de kast",
  "l'étagère": "het rek, het wandrekje",
  "la bibliothèque": "het boekenrek",
  "la télé, la télévision": "de televisie",
  "le hautparleur": "de luidspreker",
  "la console de jeux vidéo": "de spelcomputer",
  "la table de jardin": "de tuintafel",
  "le tabouret": "het krukje",
  "la lampe": "de lamp",
  "la plante": "de plant",
  "le pot de fleurs": "de bloempot",
  "le vase": "de vaas",
  "l'horloge": "de klok",
  "le réveil": "de wekker",
  "la valise": "de koffer, de valies",
};